"""added plot_id to the Project creation

Revision ID: 3da86a867079
Revises: e92e8964dcf4
Create Date: 2025-10-28 16:47:08.972564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da86a867079'
down_revision: Union[str, Sequence[str], None] = 'e92e8964dcf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=False)
    op.add_column('projects', sa.Column('plot_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_projects_plot_id'), 'projects', ['plot_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'projects', 'plots', ['plot_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'projects', 'farms', ['farm_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_plot_id'), table_name='projects')
    op.drop_column('projects', 'plot_id')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=True)
    # ### end Alembic commands ###
