"""made foreign keys nullable

Revision ID: a23295637421
Revises: 3da86a867079
Create Date: 2025-10-28 16:49:55.065612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a23295637421'
down_revision: Union[str, Sequence[str], None] = '3da86a867079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'farm_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('projects', 'plot_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'plot_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('projects', 'farm_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
